version: "3"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      TZ: "UTC"
    volumes:
      - ./data/db/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
